RevivalPMMP/PureEntitiesX

src/magicode/pureentities/PureEntities.php, src/magicode/pureentities/task/AutoDespawnTask.php
This pull request adds auto despawning to the entities in the world. Entities more than 128 blocks away from any players despawn immediatly, entities further than 32 blocks away have a 1/100 chance per second to despawn.
=> Entity auto despawning

src/magicode/pureentities/PureEntities.php, src/magicode/pureentities/task/AutoDespawnTask.php
* Add automatic despawning task.
* Add use statement.
* Fix typo
* Fix player entities getting closed 😂
* Fix player kicking and lower close rate.
* Sigh... Can't get this working.
* Now this should do the job.
* Fix other entities despawning.
* Fix despawning not happening.
=> Entity auto despawning (#14)

src/magicode/pureentities/PureEntities.php, src/magicode/pureentities/event/CreatureSpawnEvent.php, src/magicode/pureentities/task/AutoSpawnAnimalTask.php, src/magicode/pureentities/task/AutoSpawnMonsterTask.php
This pull request adds the event CreatureSpawnEvent. It can be used for developers to change the usage of the auto-spawning feature from PureEntities. This also fixes an error spam if the biome is somehow unknown.
=> CreatureSpawnEvent addition for plugin developers.

src/revivalpmmp/pureentities/entity/animal/walking/Chicken.php, src/revivalpmmp/pureentities/entity/animal/walking/Cow.php, src/revivalpmmp/pureentities/entity/animal/walking/Donkey.php, src/revivalpmmp/pureentities/entity/animal/walking/Horse.php, src/revivalpmmp/pureentities/entity/animal/walking/Mooshroom.php, src/revivalpmmp/pureentities/entity/animal/walking/Mule.php, src/revivalpmmp/pureentities/entity/animal/walking/Pig.php, src/revivalpmmp/pureentities/entity/animal/walking/Sheep.php, src/revivalpmmp/pureentities/entity/monster/flying/Blaze.php, src/revivalpmmp/pureentities/entity/monster/walking/CaveSpider.php, src/revivalpmmp/pureentities/entity/monster/walking/Creeper.php, src/revivalpmmp/pureentities/entity/monster/walking/Enderman.php, src/revivalpmmp/pureentities/entity/monster/walking/Husk.php, src/revivalpmmp/pureentities/entity/monster/walking/IronGolem.php, src/revivalpmmp/pureentities/entity/monster/walking/PigZombie.php, src/revivalpmmp/pureentities/entity/monster/walking/Skeleton.php, src/revivalpmmp/pureentities/entity/monster/walking/SnowGolem.php, src/revivalpmmp/pureentities/entity/monster/walking/Spider.php, src/revivalpmmp/pureentities/entity/monster/walking/Stray.php, src/revivalpmmp/pureentities/entity/monster/walking/WitherSkeleton.php, src/revivalpmmp/pureentities/entity/monster/walking/Zombie.php, src/revivalpmmp/pureentities/entity/monster/walking/ZombieVillager.php
I changed the item drop configuration on all the entities so that they drop what they are supposed to (according to the Minecraft wiki). Some thing were not possible to make 100% correct though, because the chances are supposed to be affected by enhancements and stuff. Anyway, I tested all the entities, and everything seem to work.
=> Correct item drops

src/revivalpmmp/pureentities/entity/animal/walking/Chicken.php, src/revivalpmmp/pureentities/entity/animal/walking/Cow.php, src/revivalpmmp/pureentities/entity/animal/walking/Donkey.php, src/revivalpmmp/pureentities/entity/animal/walking/Horse.php, src/revivalpmmp/pureentities/entity/animal/walking/Mooshroom.php, src/revivalpmmp/pureentities/entity/animal/walking/Mule.php, src/revivalpmmp/pureentities/entity/animal/walking/Pig.php, src/revivalpmmp/pureentities/entity/animal/walking/Sheep.php, src/revivalpmmp/pureentities/entity/monster/flying/Blaze.php, src/revivalpmmp/pureentities/entity/monster/flying/Ghast.php, src/revivalpmmp/pureentities/entity/monster/jumping/MagmaCube.php, src/revivalpmmp/pureentities/entity/monster/jumping/Slime.php, src/revivalpmmp/pureentities/entity/monster/walking/CaveSpider.php, src/revivalpmmp/pureentities/entity/monster/walking/Creeper.php, src/revivalpmmp/pureentities/entity/monster/walking/Husk.php, src/revivalpmmp/pureentities/entity/monster/walking/IronGolem.php, src/revivalpmmp/pureentities/entity/monster/walking/PigZombie.php, src/revivalpmmp/pureentities/entity/monster/walking/Skeleton.php, src/revivalpmmp/pureentities/entity/monster/walking/SnowGolem.php, src/revivalpmmp/pureentities/entity/monster/walking/Spider.php, src/revivalpmmp/pureentities/entity/monster/walking/Stray.php, src/revivalpmmp/pureentities/entity/monster/walking/WitherSkeleton.php, src/revivalpmmp/pureentities/entity/monster/walking/Zombie.php, src/revivalpmmp/pureentities/entity/monster/walking/ZombieVillager.php
Entities now drop items regardless of how they are killed
=> Made entities always drop items

config.yml, resources/config.yml, src/revivalpmmp/pureentities/PureEntities.php, src/revivalpmmp/pureentities/task/AutoDespawnTask.php, src/revivalpmmp/pureentities/task/AutoSpawnAnimalTask.php, src/revivalpmmp/pureentities/task/AutoSpawnMonsterTask.php
Finally, some configuration!
I tested it, and got no errors. If you find any, let me know!
=> Configuration

src/revivalpmmp/pureentities/PureEntities.php, src/revivalpmmp/pureentities/entity/BaseEntity.php, src/revivalpmmp/pureentities/entity/animal/flying/Bat.php, src/revivalpmmp/pureentities/entity/animal/walking/Chicken.php, src/revivalpmmp/pureentities/entity/animal/walking/Cow.php, src/revivalpmmp/pureentities/entity/animal/walking/Donkey.php, src/revivalpmmp/pureentities/entity/animal/walking/Horse.php, src/revivalpmmp/pureentities/entity/animal/walking/Mooshroom.php, src/revivalpmmp/pureentities/entity/animal/walking/Mule.php, src/revivalpmmp/pureentities/entity/animal/walking/Ocelot.php, src/revivalpmmp/pureentities/entity/animal/walking/Pig.php, src/revivalpmmp/pureentities/entity/animal/walking/Rabbit.php, src/revivalpmmp/pureentities/entity/animal/walking/Sheep.php, src/revivalpmmp/pureentities/entity/animal/walking/Villager.php, src/revivalpmmp/pureentities/entity/monster/flying/Ghast.php, src/revivalpmmp/pureentities/entity/monster/jumping/Slime.php, src/revivalpmmp/pureentities/entity/monster/walking/CaveSpider.php, src/revivalpmmp/pureentities/entity/monster/walking/IronGolem.php, src/revivalpmmp/pureentities/entity/monster/walking/Skeleton.php, src/revivalpmmp/pureentities/entity/monster/walking/Spider.php, src/revivalpmmp/pureentities/entity/monster/walking/Stray.php, src/revivalpmmp/pureentities/entity/monster/walking/Wolf.php, src/revivalpmmp/pureentities/entity/monster/walking/Zombie.php, src/revivalpmmp/pureentities/entity/monster/walking/ZombieVillager.php
- set health to maxHealth when setting max health in entites
- corrected some start/stopTimings
- added logfile writing to plugin
=> 1.0.0 bug fixes

plugin.yml, src/revivalpmmp/pureentities/PureEntities.php, src/revivalpmmp/pureentities/entity/animal/walking/Sheep.php, src/revivalpmmp/pureentities/event/EventListener.php
- added summon command for better bug fixing (summon is a "normal" command in MCPE normally)
- changed shearing sheeps bugfix (when a sheep was in level, the shear button was shown on every entity)
- sheeps no drop correct wool color when sheared
1.0.0-bug-fixes
Shearing is now better but not perfect. Somehow the handling is a little weird. But it works. In the version before, it was possible to shear wolfes etc. pp - when only a sheep was available near (ok, it was not possible, but the button was shown). Maybe, i can find another solution.
=> Shearing Sheep fix(es), added summon command

plugin.yml
added support for new API3 version
1.0.0 Bug Fixes
Can I be allowed to directly edit the branch for efficiency's sake?
=> added support for new API3 version

.pullapprove.yml
I need @magicode1 to approve this in a review for the use of pullapprove
=> I need @magicode1 to approve this in a review

.gitignore, .pullapprove.yml
Added @Skull3x to Developers list
=> Added @Skull3x to Developers list

.pullapprove.yml
=> Fixing the most annoying issue

.gitignore, src/revivalpmmp/pureentities/PureEntities.php, src/revivalpmmp/pureentities/entity/animal/flying/Bat.php
Fixes Poggit's Lint check error
master
none
=> Fixed Poggit lint error

.pullapprove.yml, README.md
=> Update README.md and other admin stuff

.travis.yml
This is a small change to the .travis.yml to make sure that travis is working properly
master
none
=> Travis fix for @Magicode 's mistake

.pullapprove.yml, .travis.yml, Travis.php
Attempts to solve the travis errors
master
none
=> Solve the travis errors and add kniffo to .pullapprove

src/revivalpmmp/pureentities/entity/monster/walking/IronGolem.php
It's not allowed to have entities with health greater than 20, it could be found in Attribute class in Pocketmine-MP repo.
So this PR should fix that.
=> Fix max health for entity

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE, .poggit.yml
This PR adds other branches to be compiled in the .poggit.yml and changes the templates for issues and PRs
master
none
=> Update .poggit.yml and the default 

README.md
Added some Information on Poggit and where to find stable builds. 
Master
https://poggit.pmmp.io/p/PureEntitiesX is our release page 😄
=> Added Poggit Information

src/revivalpmmp/pureentities/utils/MobDamageCalculator.php
these conditions are redundant. getEnchantments() never returns null, and a foreach on an empty array is perfectly fine.
=> Simplify EPF calculation conditions

src/revivalpmmp/pureentities/components/IdlingComponent.php, src/revivalpmmp/pureentities/entity/BaseEntity.php, src/revivalpmmp/pureentities/entity/WalkingEntity.php, src/revivalpmmp/pureentities/entity/animal/walking/Rabbit.php, src/revivalpmmp/pureentities/entity/monster/walking/Skeleton.php
- [] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
This 'should' improve block detection colliding with the entity.
Skeleton OnFire logic has been improved, and can survive when not under ray sun.
N/A ?
N/A
=> Jump logic fixing / Skeleton OnFire fixing
